server:
  port: 8080

spring:
  datasource:
    url: YOUR_URL

    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false

google:
  api:
    key: "YOUR_API_KEY"